### ISSUE TITLE
[Project proposal] Lovelace (and assorted libraries)

### ISSUE THREAD

**Issue by teymour-aldridge** [rust-ldn/rust-hack-and-learn#10]
**Project name**: Lovelace
**Project details**: An open source edtech platform. [The repository](https://github.com/lovelace-edu/lovelace)

**Short bio**: I try to write software as a craft, rather than seeing it as a scientific discipline.
**Looking for**: Anyone! I don't have a complete idea as to what the platform should look like (it's completely a prototype at this stage) so I am open to suggestions :)

In terms of things which could be interesting to work on:
- as part of the application I've written a library called Malvolio which is a builder syntax library for constructing HTML. It's still a bit rough around the edges though and could do with a lot of tidying up.
- I have a caldav client called prospero which I would like to publish to crates.io. It's currently quite messy, however and needs a lot more tidying up (and tests!)
- I'm also working on a CSS in Rust solution (called Mercutio) which I would like to add support for the Yew web framework to. Currently it adds styles directly to Malvolio (see above) or can output CSS classes. Basically this means adding a trait with a single member called "CLASS" that is a constant and then having a way to either apply styles through DOM manipulation or have the proc macro write them to a file that can be included into the document.
- A proc derive macro to compose together Mercutio styles would also be good
- Adding support for CSS animations to Mercutio is another possible idea
- Adding support for hover animations is closely related
- I think this is a bit tricky, but it would be nice to collect code coverage for the procedural macro (see above) – I'm using tarpaulin which has support for function like proc macros but unfortunately not derive macros; this would mean writing a library that adds that support.
- Increasing the very low code coverage (not for the sake of increasing code coverage, but to make sure things work though :D)
- possibly: some dashboard pages to give people an overview of upcoming events
- also possibly: a search system to quickly find things in the application

**Comment by teymour-aldridge** [comment]
Basically this project currently has unlimited work suited for different skill levels.

"Beginners" are absolutely welcome!!!

**Comment by enaut** [comment]
Could you add links to the repositories?

**Comment by teymour-aldridge** [comment]
Oh sorry – of course :)
