### ISSUE TITLE
[Project proposal] Add support for .cargo/config.toml to cargo-chef

### ISSUE THREAD

**Issue by LukeMathWalker** [rust-ldn/rust-hack-and-learn#2]
**Project name**: Add support for .cargo/config.toml to cargo-chef

**Project details**: Address https://github.com/LukeMathWalker/cargo-chef/issues/26 - you'll get to know more about how `cargo` works!

**Short bio**: I am the maintainer of `cargo-chef`! I've been playing with Rust for a few years, both professionally and for fun.

**Looking for**: Basic Rust knowledge should be more than enough to tackle the problem - one or two people? I'm happy to mentor you on how the codebase is structured and where the new piece would fit in its architecture.

**Comment by ndaultryball1** [comment]
I'd be interested in having a go at this, although my rust experience is quite limited.

**Comment by LukeMathWalker** [comment]
Awesome 😁

**Comment by PunitLodha** [comment]
Is this still open? I would also like to join. 
I am a beginner in rust, and would love to learn more by working with a mentor

**Comment by LukeMathWalker** [comment]
Definitely still open!
There are a few other open issues at a beginner level on `cargo-chef`, so I am sure we won't be running out of work during the session 😁
