### ISSUE TITLE
[Project proposal] spotify-tui

### ISSUE THREAD

**Issue by Rigellute** [rust-ldn/rust-hack-and-learn#4]
**Project name**: spotify-tui
**Project details**: Spotify for the terminal written in Rust 

![Demo](https://user-images.githubusercontent.com/12150276/75177190-91d4ab00-572d-11ea-80bd-c5e28c7b17ad.gif)

**Short bio**: I'm the author and maintainer of `spotify-tui`! In my day job, I'm a full stack software engineer building backends/frontends/infra and mobile apps (mostly in Typescript/nodejs/React/React Native/AWS etc.). I've been using Rust for around 3 years in various side projects, and honestly enjoy using Rust more than any other language!

**Looking for**: Basic Rust knowledge is all that's needed to solve a number of issues! `spotify-tui` has grown into a fairly large project but has greatly benefited from contributors of all skill levels. Most contributors (I believe) are fairly new to Rust but have had a large impact in fixing bugs/adding new features.

I will post some open issues and try to gauge the level of Rust knowledge required.

**Comment by Rigellute** [comment]
Some example issues, for different levels:

### Issue

Rendering of Tickrate and Framerate a bit confusing [#626](https://github.com/Rigellute/spotify-tui/issues/626).

### Rust knowledge: basic

We could implement the proposed solution (updating the displayed string formatting). Or perhaps we could create a new cli argument (using clap) to explicitly set an FPS value.

---

### Issue

[Feature Request] Hide unplayable songs [#718](https://github.com/Rigellute/spotify-tui/issues/718)

### Rust knowledge: basic

We can use the spotify API to filter our tracks that are playable or not

---

### Issue

Upgrade crates with breaking changes: `tui`, `rand`, `cross-term`.

### Rust knowledge: intermediate

This one is more involved as it requires some knowledge of the breaking changes and where in `spotify-tui` they need fixing.

--- 

### Issue 

Pagination of spotify responses is currently handled rather poorly throughout the app. Needing an abstraction to make it easier to work with.

### Rust knowledge: advanced

**Comment by Hwatwasthat** [comment]
I'd be interested in working on this, I'd be happy to take the unplayable songs issue :) If I finish that I could hop onto other things too!

**Comment by MaxLuchs** [comment]
Im also interested in this. Sounds cool. Have basic Rust knowledge.

**Comment by MaxLuchs** [comment]
Do you have another issue for  me where basic rust knowledge is sufficient? Maybe I'll try to upgrade those packages.

**Comment by elbart** [comment]
I'd be interested here, too. Basic rust knowledge is in place, I'd say.
