### ISSUE TITLE
[Project proposal] Exercism rust track

### ISSUE THREAD

**Issue by gilescope** [rust-ldn/rust-hack-and-learn#5]
**Project name**: Exercism rust track
**Project details**: Together fumble our way through https://exercism.io/tracks/rust exercises.
**Short bio**: I'm one of the exercism rust mentors. I'll try and make sure that you get very fast turn around on your submissions and get quick feedback for the duration of the event and be on hand in the discord to chat to if there's questions / problems.
**Suitable for**: The exercises start simple and gradually get harder so any level of rust exerience is fine to jump in and have a go.

**Comment by EnzoPlayer0ne** [comment]
I'd love to take part in this! Is there anything you recommend doing before the Hack & Learn?

**Comment by gilescope** [comment]
Feel free to have a go at one or two opening exercises. If you need a rust IDE setup then VS Code with the "rust in peace" extensions will get you up and running.

**Comment by billkouts** [comment]
I also want to take part in this !

**Comment by billkouts** [comment]
> Feel free to have a go at one or two opening exercises. If you need a rust IDE setup then VS Code with the "rust in peace" extensions will get you up and running.

@gilescope I see there are two `rust in peace` VS Code extensions; one from you and one from a user `chapmandu`.
I assume it's your extension pack were talking about right?

Leaving this here for visibility

**Comment by dr-sholmes** [comment]
Hi, I'd also be interested in joining in with this!

**Comment by dailyprice** [comment]
I would love to join Giles!

**Comment by gilescope** [comment]
Great - looking forward to it. The more the merrier!

**Comment by aeroaks** [comment]
Hi, I am very much interested in joining this.

**Comment by alessio4tech** [comment]
Hi, I'd like to join as well :)

**Comment by gilescope** [comment]
Looking forward to tomorrow!

**Comment by aeroaks** [comment]
I have done the setup for VScode. Just want to mention that your extension is not visible in [Codium](https://github.com/VSCodium/vscodium/).

**Comment by mbracher** [comment]
I would be interested in finding out/getting-help with benchmarking and profiling. I'm currently doing the Anagram exercise. It mentions to choose faster sorting and preventing duplicate work. I have passing tests but would like to see how much effect any changes have (using criterion benchmarking). And maybe also profiling so see where changes would have the most effect. Is this something for this Project/Channel?

**Comment by enaut** [comment]
@mbracher so hop into discord and join the discussion: https://discord.gg/jY2xQV2p9v
